#!/usr/bin/with-contenv bash

cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_|_|_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

# permissions
chown -R abc:abc \
	/data

apt-get update && apt-get install -y unzip

# install the trakt plugin
wget https://github.com/pannal/Sub-Zero.bundle/releases/download/2.6.5.3109/Sub-Zero.bundle-2.6.5.3109.zip && \
unzip Sub-Zero.bundle-2.6.5.3109.zip -d "/config/Library/Application Support/Plex Media Server/Plug-ins/" && \
rm Sub-Zero.bundle-2.6.5.3109.zip

# allow all users to access GPU for hardware acceleration
chmod -R 777 /dev/dri
